import React from 'react';
import ReactDOM from 'react-dom/client';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { theme } from './theme';
import './index.css';
import { AppDataProvider } from './context/AppDataContext';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <AppDataProvider>
        <App />
      </AppDataProvider>
    </ThemeProvider>
  </React.StrictMode>
);

// Register the service worker generated by vite-plugin-pwa for offline support.
if ('serviceWorker' in navigator) {
  import('virtual:pwa-register')
    .then(({ registerSW }) => registerSW({ immediate: true }))
    .catch(() => {
      // Not running in a PWA-built context (e.g. plain `vite dev` without the plugin ready) — ignore.
    });
}
